### ISSUE TITLE
Отгрузка данных партнерам

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/webnabludatel_server#10]
Необходимо обеспечить интерфейс отгрузки данных партнерам - профиль наблюдателя + лента изменений. Профиль содержит в себе полную версию чеклиста + ссылки на SOS-сообщения.

Лента изменений - пользователь/девайс, измененные поля, статус "нарушение или нет", timestamp.

Формат
Профиль - xml
лента - rss

защита - Basic Auth

**Comment by codesnik** [comment]
хейхей.

нужны данные от консумеров - что именно их интересует.

плюс для изменений понадобится какой-то механизм логирования или аудита, а эту штуку неглядя привинчивать не стоит. - нужно четко понимать потребности.

**Comment by codesnik** [comment]
скаффолд для апи в мастере, если что.
но, вероятнее всего, там понадобится какой-то простой презентер с кастомным to_xml

**Comment by codesnik** [comment]
просто профили никто использовать уже не успеет.
есть вот такая штука
https://docs.google.com/document/d/1EoPte_WGrpvfCceUEsqBBKH8wM5rTXXQfQfTgabwvws/edit?pli=1

полезная и после выборов

**Comment by codesnik** [comment]
таск, наверное, сдаю. кроме как реализовать доку выше, по-моему, никому ничего не надо.
