### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by alec-c4** [webnabludatel/webnabludatel_server#15]
Статистические данные с разбивкой по городам
- топ 10 нарушений
- топ 10 городов с нарушителями
- топ 10 участков-нарушителей
- топ 10 наблюдателей по количеству найденных нарушений
- графики с нарушениями по основным городам
- фото финальных отчетов (есть, но надо ссылку вывести)

**Comment by codesnik** [comment]
- топ 10 нарушений: 

уже на http://webnabludatel.org/reports (но линки там никуда не ведут)
- топ 10 городов с нарушИТЕЛЯМИ? (участками, видимо)

и, видимо, регионов. сделаю на этой же странице.
- топ 10 участков-нарушителей:

уже на /reports, спасибо кому-то.
- топ 10 наблюдателей по количеству найденных нарушений

будет криво, но ок, туда же выведу, для начала.
- графики с нарушениями по основным городам

не знаю пока, что такое "основной город", и какие там могут быть графики. вот эта красно-синяя фигня, но не тотал, а по региону?
- фото финальных отчетов (есть, но надо ссылку вывести)

не читал пока

**Comment by alec-c4** [comment]
Остались актуальными
- топ 10 городов с нарушИТЕЛЯМИ? (участками, видимо)
- топ 10 наблюдателей по количеству найденных нарушений
- графики с нарушениями по основным городам (Москва, СПБ, Екатеринбург и др города по убыванию нарушений в них), да - та самая "фигня" :)

а также
- общая статистика по нарушениям (аналогично топ10, но со всеми нарушениями - на отдельной странице)

**Comment by codesnik** [comment]
http://webnabludatel.ru/regions

добавил туда количество рапортовавших наблюдателей (через комиссии и вотчер-репорты) по регионам.
линк в шапке закомментировал, меню расползается.

в /reports топ уменьшил до восьми.

что с  этим делать - up to you.
