### ISSUE TITLE
Настроить staging для тестирования

### ISSUE THREAD

**Issue by nebolsin** [webnabludatel/webnabludatel_server#6]

**Comment by codesnik** [comment]
откликается на 
http://ec2-176-34-68-134.eu-west-1.compute.amazonaws.com/

**Comment by nebolsin** [comment]
Можно закрывать этот тикет? Или он еще нужен?

**Comment by codesnik** [comment]
хз, мне не нужен. в него можно ходить, чтобы хостнейм скопировать!

**Comment by nebolsin** [comment]
Ходить можно и в закрытый, закрываю чтобы глаза не мозолил.
